services:
    browser:
      image: nishithp/spectra-browser
      build: ./browser
      platform: linux/amd64
      restart: unless-stopped
      ports: 
        - "7900:7900" # noVNC Interface
        - "8921:8921" # Playwright MCP Server
        - "8922:8922" # pyautogui MCP Server
      environment:
        - ENABLE_RECORDING=false
        - RTMP_URL=rtmp://rtmp-server/stream/browser-session-recording
      depends_on:
        - rtmp-server
      networks:
        - spectra-net

    rtmp-server: 
      image: nishithp/spectra-rtmp-server
      build: ./rtmp-server
      restart: unless-stopped
      ports:
        - "1935:1935" # RTMP Port
        - "8080:80" # Web Interface 
      volumes: 
       - ./rtmp-server/credentials.json:/app/credentials.json
      networks:
        - spectra-net

    agent: 
      image: nishithp/spectra-agent
      build: ./agents
      restart: unless-stopped
      ports:
        - "8000:8000" # Web Interface
      env_file: 
        - "./agents/.env"
      depends_on:
        - browser
        - pentools
        - cyberchef-mcp
      networks:
        - spectra-net

    pentools:
      image: nishithp/spectra-pentools
      build: ./tools/pentools
      platform: linux/amd64
      restart: unless-stopped
      ports:
        - "5002:5000" # API Server
        - "5001:5001" # MCP Server
      networks:
        - spectra-net
    
    cyberchef-server:
      image: nishithp/spectra-cyberchef-server
      build: ./tools/cyberchef/CyberChef-server
      restart: unless-stopped
      ports: 
        - "3000:3000"
      networks:
        - spectra-net
    
    cyberchef-mcp:
      image: nishithp/spectra-cyberchef-mcp
      build: ./tools/cyberchef/cyberchef-api-mcp-server
      restart: unless-stopped
      ports:
        - "3001:3000"
      environment:
        - CYBERCHEF_API_URL=http://cyberchef-server:3000/
      depends_on:
        - cyberchef-server
      networks:
        - spectra-net

    redis:
      image: redis:latest
      restart: unless-stopped
      ports:
        - "6379:6379"
      networks:
        - spectra-net

    router:
      image: nishithp/spectra-router
      build: ./router
      restart: unless-stopped
      ports:
        - "80:80"
      env_file: 
        - "./router/.env"
      volumes: 
       - ./router/credentials.json:/app/credentials.json
      depends_on:
        - redis
      networks:
        - spectra-net

networks:
  spectra-net: 
    driver: bridge
