apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
  labels:
    app: router
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      serviceAccountName: router-sa 
      containers:
        - name: router
          image: nishithp/spectra-router:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: spectra-env-secret
          volumeMounts:
            - name: spectra-credentials
              mountPath: /app/credentials.json
              subPath: credentials.json
      volumes:
        - name: spectra-credentials
          secret:
            secretName: spectra-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: router-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: router-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60