apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: user-{{UID}}
spec:
  selector:
    app: spectra-interactive-session
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: browser-service
  namespace: user-{{UID}}
spec:
  selector:
    app: spectra-interactive-session
  ports:
    - protocol: TCP
      name: vnc
      port: 7900
      targetPort: 7900
---
apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
  namespace: user-{{UID}}
spec:
  selector:
    app: spectra-rtmp-session
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935